### ISSUE TITLE
자세하게 설명해주실수있나요

### ISSUE THREAD

**Issue by INFINITYHit** [zxc010613/autohotkey-server-login-register#2]
연락할수단이 있으면 좋겠습니다

**Comment by mschadev** [comment]
제가 너무 늦게 봤네요. 깃허브 이슈 코멘트로도 말씀해주셔도 됩니다.

그외 연락수단은
카톡 오픈채팅방: https://open.kakao.com/me/plorence
텔레그램: https://t.me/plorence
중 하나로 연락주시면 됩니다.
